name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build formatter_ex_lib
      run: mkdir formatter_ex_lib/build && cd formatter_ex_lib/build && cmake .. && make

    - name: build solver_lib
      run: mkdir solver_lib/build && cd solver_lib/build && cmake .. && make

    - name: build solver_application
      run: mkdir solver_application/build && cd solver_application/build && cmake .. && make

